[config]
schemaVersion = "0.0.1"

[package]
namespace = "Sparroh"
name = "AmalgamationTracker"
description = "Tracks Amalgamation boss fight time with an on-screen timer from spawn to kill."
websiteUrl = "https://github.com/Little-Sparroh/AmalgamationTracker"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_Mycopunk = "5.4.2403"
Sparroh-SparrohUILib = "1.2.0"


[build]
icon = "icon.png"
readme = "README.md"
outdir = "build"

[[build.copy]]
source = "bin/Release/netstandard2.1/AmalgamationTracker.dll"
target = "BepInEx/plugins/AmalgamationTracker.dll"

[[build.copy]]
source = "CHANGELOG.md"
target = "CHANGELOG.md"

[[build.copy]]
source = "LICENSE"
target = "LICENSE"

[publish]
repository = "https://thunderstore.io"
communities = ["mycopunk"]

[publish.categories]
mycopunk = ["client"]
